### ISSUE TITLE
Looking for shape file

### ISSUE THREAD

**Issue by bimeobed** [bimeobed/Spatial_-layers#1]
@mmindje  How to produce that shapefile

**Comment by mmindje** [comment]
Thank you @bimeobed

**Comment by mmindje** [comment]
What link can I use to get the shapefiles @bimeobed

**Comment by bimeobed** [comment]
> What link can I use to get the shapefiles @bimeobed

https://data.humdata.org/dataset/rwanda-administrative-boundaries-level-1-4

**Comment by mmindje** [comment]
That is great I got this 
![image](https://user-images.githubusercontent.com/64961274/98102100-dce9b500-1e9b-11eb-9726-4510cbf72f14.png)
where should I click??? what are the processes?
